# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



# No code solution (reading)
done, will go through again if needed

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.5852, 0.7536, 0.3693, 0.6655, 0.3719, 0.3409, 0.6681],
        [0.8497, 0.2418, 0.7977, 0.6970, 0.5196, 0.6372, 0.1117],
        [0.3736, 0.3005, 0.9243, 0.5796, 0.8938, 0.6547, 0.3577],
        [0.8501, 0.1053, 0.2750, 0.3129, 0.2328, 0.9975, 0.6772],
        [0.7342, 0.0582, 0.7818, 0.9384, 0.9144, 0.5171, 0.7118],
        [0.9285, 0.5583, 0.5622, 0.1826, 0.9430, 0.3501, 0.3879],
        [0.5850, 0.0546, 0.8676, 0.0930, 0.9762, 0.4359, 0.1063]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor_1 = torch.rand(1,7)
tensor_1
# Perform matrix multiplication
matrix_1 = torch.matmul(tensor, tensor_1.T)
matrix_1

tensor([[1.6578],
        [1.6532],
        [1.6398],
        [1.6064],
        [2.0429],
        [1.9959],
        [1.4298]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
RANDOM_SEED = torch.manual_seed(0)


# Create two random tensors
tensor = torch.rand(7,7)
tensor_1 = torch.rand(1,7)

# Matrix multiply tensors
matrrix = tensor.matmul(tensor_1.T)
print(matrrix)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
RANDOM_SEED = torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
RANDOM_SEED = torch.cuda.manual_seed(1234)
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
tensor = torch.rand(2,3).cuda()
tensor_1 = torch.rand(2,3).cuda()
print(tensor)
print(tensor_1)

tensor([[0.0340, 0.9442, 0.8802],
        [0.0012, 0.5936, 0.4158]], device='cuda:0')
tensor([[0.4177, 0.2711, 0.6923],
        [0.2038, 0.6833, 0.7529]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
matrixx = torch.matmul(tensor, tensor_1.T)
matrixx, matrixx.shape

(tensor([[0.8795, 1.3148],
         [0.4493, 0.7189]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
maxx = torch.max(matrixx)
# Find min
minn = torch.min(matrixx)
maxx, minn

(tensor(1.3148, device='cuda:0'), tensor(0.4493, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [23]:
# Find arg max
argg = torch.argmax(matrixx)
# Find arg min
arggg = torch.argmin(matrixx)
argg, arggg

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
RANDOM_SEED = torch.manual_seed(7)
# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_rem = tensor.squeeze()

# Print out tensors and their shapes
tensor, tensor.shape, tensor_rem, tensor_rem.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))