In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


creatiing tensors


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

why random tensors?

random tensors are important because the way many neural nets learn is taht they start with full of random numbers and then adjust those random numbers to bettter represent the data

start with random numbers- > look at data  ->update random numbers -> look at data -> update random numbers

In [17]:
#creating a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0373, 0.0458, 0.4921, 0.0087],
        [0.3929, 0.6702, 0.5880, 0.1888],
        [0.7210, 0.4330, 0.7164, 0.7293]])

In [18]:
random_tensor.ndim

2

In [19]:
#create a trandom tensor with similar shape to an image tensor
random_tensor_image = torch.rand(size=(224,224,3))
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

## creating a range of tensors and tensors - like

In [25]:
#use torch.range()\
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#creting tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##tensor datatypes

tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning
1. tensors not right datatyep
2. tensors not eright shape
3. tensors not on the right device

In [27]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what datatype is the tenspr
                               device=None, #
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### getting info from tensors (tensor attributes)

1. tensors not right datatyep - use 'tensor.dtype'
2. tensors not eright shape - use 'tensor.shape'
3. tensors not on the right device - use 'tensor.device'

### Manipulating Tensors (tensor operations)

tensor operations include :
* addition
* subtraction
* multiplication
* division
* matrix multiplication

In [33]:
#create a tensor
tensor = torch.tensor([1,2,3])

tensor+10

tensor([11, 12, 13])

In [34]:
tensor*3

tensor([3, 6, 9])

In [35]:
tensor - 1010

tensor([-1009, -1008, -1007])

In [36]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor, 100000)

tensor([100001, 100002, 100003])

###matrix multiplication

two main methods of performing multiplication in neural netrs and DL
1. element wise
2. matrix multipliaction (dot product)


In [38]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [39]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
# matrix multplication by hand
1*1 + 2*2+ 3*3

14

### one of the most common errors in matmul are shape errrors

there are two main rules that performing matrix multi need to satisfy
1. the inner dimensions must match
* (3,2) @ (3,2) won't work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work

2. the resulting matrix has the shape of the outer dimensions
* `(2,3) @ (3,2)` => (2,2)
* `(3,2) @ (2,3)` -> (3,3)


In [41]:
#shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [42]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### finding the min, max, mean, sum, etc (tensor aggregation)

In [43]:
x = torch.arange(0,100, 10)

In [44]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [46]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [47]:
#find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [48]:
x.type(torch.float32).mean()

tensor(45.)

In [49]:
x.sum()

tensor(450)

In [50]:
torch.sum(x)

tensor(450)

### finding the positional min and max

In [51]:
#find the psoition in tensor that has the minimum value with argmin() -=> returns the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [52]:
x.argmax()

tensor(9)

## reshaping, stacking, squeezing and unsqueezing tensors
* reshapeing = reshapes an input tensor to a defined shape
* view = return a view of an input tensor but keep the same memory as the original tensor
*  stacking - combine multiple tensors on top of each other (v stack) and (h stack)
* squeeze = remves all '1' dimension from a tensor
* unsqueez = add a '1' dimension to a taregt tensor
* permute = return a view of the input with dimensions permuted (swapped) in a certain way

In [53]:
x = torch.arange(1., 10.)

In [54]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
#changing z changes x because the view of a tensor shares the asame memory ass the tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [58]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [59]:
x_reshaped.shape

torch.Size([1, 9])

In [60]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
x_reshaped.squeeze().shape

torch.Size([9])

In [63]:
x_unsqueezed = x_reshaped.squeeze()
x_unsqueezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
x_original = torch.rand(size=(224,224,3))
x_original

tensor([[[0.6369, 0.4222, 0.2941],
         [0.6526, 0.3134, 0.9695],
         [0.9694, 0.6775, 0.1666],
         ...,
         [0.0311, 0.9517, 0.3650],
         [0.3496, 0.2297, 0.4944],
         [0.2863, 0.8659, 0.1013]],

        [[0.9155, 0.9070, 0.6665],
         [0.4277, 0.9907, 0.6521],
         [0.9139, 0.8346, 0.3976],
         ...,
         [0.9647, 0.3504, 0.5479],
         [0.2974, 0.0883, 0.6684],
         [0.8666, 0.0322, 0.3050]],

        [[0.2903, 0.4201, 0.3487],
         [0.7341, 0.3098, 0.4565],
         [0.6549, 0.0690, 0.5373],
         ...,
         [0.8253, 0.3940, 0.1858],
         [0.9025, 0.3877, 0.3954],
         [0.0685, 0.4892, 0.6893]],

        ...,

        [[0.6543, 0.3962, 0.3148],
         [0.1163, 0.8876, 0.2237],
         [0.4352, 0.8419, 0.0944],
         ...,
         [0.2310, 0.4670, 0.7453],
         [0.2850, 0.4327, 0.2580],
         [0.6955, 0.7996, 0.4064]],

        [[0.2036, 0.6802, 0.1925],
         [0.1907, 0.6326, 0.0886],
         [0.

In [65]:
x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.6369, 0.6526, 0.9694,  ..., 0.0311, 0.3496, 0.2863],
         [0.9155, 0.4277, 0.9139,  ..., 0.9647, 0.2974, 0.8666],
         [0.2903, 0.7341, 0.6549,  ..., 0.8253, 0.9025, 0.0685],
         ...,
         [0.6543, 0.1163, 0.4352,  ..., 0.2310, 0.2850, 0.6955],
         [0.2036, 0.1907, 0.1242,  ..., 0.2584, 0.3671, 0.2053],
         [0.5920, 0.5541, 0.7334,  ..., 0.2734, 0.7176, 0.7598]],

        [[0.4222, 0.3134, 0.6775,  ..., 0.9517, 0.2297, 0.8659],
         [0.9070, 0.9907, 0.8346,  ..., 0.3504, 0.0883, 0.0322],
         [0.4201, 0.3098, 0.0690,  ..., 0.3940, 0.3877, 0.4892],
         ...,
         [0.3962, 0.8876, 0.8419,  ..., 0.4670, 0.4327, 0.7996],
         [0.6802, 0.6326, 0.5546,  ..., 0.2865, 0.2119, 0.3259],
         [0.7024, 0.2323, 0.8907,  ..., 0.0856, 0.3654, 0.6109]],

        [[0.2941, 0.9695, 0.1666,  ..., 0.3650, 0.4944, 0.1013],
         [0.6665, 0.6521, 0.3976,  ..., 0.5479, 0.6684, 0.3050],
         [0.3487, 0.4565, 0.5373,  ..., 0.1858, 0.3954, 0.

In [66]:
x_permuted.shape

torch.Size([3, 224, 224])

### indexing (selectoing data from tensors)

indexing with pytorch is similar to indexing with numpy

In [67]:
x = torch.arange (1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [68]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
x[0][0]

tensor([1, 2, 3])

In [70]:
x[0][0][0]

tensor(1)

In [72]:
x[0][1][1]

tensor(5)

In [73]:
x[:, 0]

tensor([[1, 2, 3]])

In [74]:
x[:,:,1]

tensor([[2, 5, 8]])

## pytorch tensors & numpy

* data in numpy but want in pytorch tensor -> torch.from_numpy(ndarray)
* pytorch tensor -> numpy -> torch.tensor.numpy()

In [75]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducibility (trying to take random out of random)

in short how a neural network lerns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again > ...


to reduce the randomness in neural nets and pytorch comes the concept of **random seed**

what seed does is *flavour* the randomness

In [78]:
torch.rand(3,3)

tensor([[0.2030, 0.6370, 0.9079],
        [0.3292, 0.3678, 0.0819],
        [0.8076, 0.0035, 0.0431]])

In [80]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5127, 0.6531, 0.6774, 0.8354],
        [0.6202, 0.1320, 0.6613, 0.3431],
        [0.5077, 0.1053, 0.5637, 0.8400]])
tensor([[0.1290, 0.1503, 0.5850, 0.4536],
        [0.0789, 0.2622, 0.0402, 0.2294],
        [0.0363, 0.4311, 0.2060, 0.0838]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
